### ISSUE TITLE
No instance nor default method for class operation basicInitialize

### ISSUE THREAD

**Issue by divipp** [mokus0/bitvec#2]
When I try to install bitvec on NixOS, it runs bitvec-tests which fails with the following error message:

    Exception:
      src/Data/Vector/Unboxed/Bit/Internal.hs:110:10-33: No instance nor default method for class operation basicInitialize

**Comment by mokus0** [comment]
I just ran into this the other day as well - looks like a newer version of the `vector` library added these methods, so I'll need to implement them here.

**Comment by mokus0** [comment]
actually it appears I fixed this a while ago but didn't upload to Hackage for some reason.  I'll do some quick sanity checks and upload.

**Comment by mokus0** [comment]
This should be fixed in 0.1.0.2, which i've just pushed to hackage.

**Comment by divipp** [comment]
Thanks!
